export type UserData = {
    created_at: string,
    current_team_id: any,
    deleted_at: any,
    egrpou: string,
    company: string,
    email: string,
    email_verified_at: string,
    firstName: string,
    guid: string,
    id: number,
    lastName: string,
    mGuid: string,
    mMail: string,
    mName: string,
    mPhone: string,
    middleName: string,
    name: string,
    phone: string,
    profile_photo_path: any,
    profile_photo_url: string,
    role: string,
    two_factor_confirmed_at: any,
    updated_at: string,
};